### ISSUE TITLE
Incompatibility with double slabs (Crash on startup)

### ISSUE THREAD

**Issue by Umbraminf** [MythrilBagels/Create-Alloyed#112]
Hi, your mod seems to be incompatible with Double Slabs, it just crashes on startup.

alloyed-1.16.5-v0.3a
DoubleSlabs-1.16-3.7.3
Forge 36.2.34
Minecraft 1.16.5

[debug.log](https://github.com/MythrilBagels/Create-Alloyed/files/14320520/debug.log)
[crash-2024-02-17_20.58.09-client.txt](https://github.com/MythrilBagels/Create-Alloyed/files/14320519/crash-2024-02-17_20.58.09-client.txt)
[latest.log](https://github.com/MythrilBagels/Create-Alloyed/files/14320518/latest.log)

My computer:
AMD Ryzen 3 3200G with Radeon Vega Graphics       3.60 GHz
8.00 GB (usable: 5.95 GB)
Windows 11 Pro 22H2

**Comment by Barerock** [comment]
I believe this was fixed for create as a whole in subsequent versions. I myself made an initial report for it around that time on the create page, I would look there instead. Alloyed may be interacting with create to do something between the two mods and they conflict, causing an error.
