### ISSUE TITLE
Leaves Decay/Break into Leaves...

### ISSUE THREAD

**Issue by Gantros** [MythrilBagels/Create-Alloyed#12]
VERSIONS
Minecraft - 1.18.1
Create - 0.4d
Flywheel - 1.18-0.6.0
Alloyed - 1.18.1-v0.1

DESCRIPTION
Breaking any leaf block results in the dropping the whole block, not destroying it or droppin g sticks/apples/saplings/etc. It's as if one were using shears or silk touch, even when not using any tools at all. Even cutting the tree down results in leaf decay dropping only whole leaf blocks.

STEPS TO REPRODUCE
simply break any leaf block by any means.

**Comment by ghost** [comment]
Can confirm. WTF? How does this even happen?

**Comment by FortressNebula** [comment]
Yep, this is a known issue. The loot tables used to get the steel shears working seem to be broken? Even though they work in the dev environment? We're investigating it.
