### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by Tsunamori74** [MythrilBagels/Create-Alloyed#14]
Alloyed crashes on startup, my mod list is fairly lenghty but I'm fairly certain from testing everything that alloyed is the source of the crash. Log appended. Seems to be a mixins problem?

[latest.log](https://github.com/MythrilBagels/Create-Alloyed/files/8018092/latest.log)

**Comment by FortressNebula** [comment]
Could you redo this issue following the template?

**Comment by FortressNebula** [comment]
Also, you appended the log, which isn't all that helpful. A crash report would be needed to properly diagnose the issue.
