### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by Tsunamori74** [MythrilBagels/Create-Alloyed#15]
VERSIONS
Minecraft - 1.18.1
Create - 1.18.1_v0.4d
Flywheel - 1.18-0.6.0
Alloyed - 1.18.1-v0.1

DESCRIPTION
Game fails to startup, log mentions mixins error. I would append a crash log, but one was not generated. The game did not have a chance to start (open the Minecraft window) so all I had was the plain console log. If I had a crash log, I would submit it, I am aware that it is more helpful than a regular Minecraft log.

STEPS TO REPRODUCE
1. Launch Minecraft
2. Crash

**Comment by FortressNebula** [comment]
So you've confirmed that Create: Alloyed is the source of the crash?

**Comment by Tsunamori74** [comment]
I take out the mod and the game stops crashing, yes. It’s the only mod that is causing the crash.

**Comment by FortressNebula** [comment]
Hmm, it's weird that no crash report is made. Can you try to locate the exact mod that Create: Alloyed is having an incompatibility with? (I'd say do a binary search)

**Comment by FortressNebula** [comment]
Alright I haven't heard anything about this issue so it's being marked as stale. The issue will be closed in a week or so if no further info is provided.

**Comment by The-Bernician-Lamb** [comment]
I just want to jump in here and say that I've been having this same issue after I downloaded this mod to try it out earlier today. It doesn't generate a crash report and the log shows a mixin error. I'm using the same versions as the person who reported it here but with the latest version of Alloyed (0.1b). My Forge Version is 39.0.76 if that helps.

Latest Log (No crash report is generated): https://gist.github.com/NJL5390/4e7767219a215edbad987dc6e99e2800

Finally, to answer your question on mod incompatibilities, there are none. This crash happens without any other mods installed aside from alloyed and it's dependencies. I hope this helps.

**Comment by FortressNebula** [comment]
Huh, thats strange. Downloading the jar from curseforge causes the error, but building the jar from my dev environment doesn't! I'll have to look into that. For now the broken upload is being removed and the fixed one should be coming up soon.
