### ISSUE TITLE
Compatibility with Tetra?

### ISSUE THREAD

**Issue by Canada-LaVearn** [MythrilBagels/Create-Alloyed#16]
So basically my idea is to make the materials work with the Tetra mod, so they can be used for tool heads, handles, etc.
This request is made partially because I may be using this in a modpack that contains Tetra.

Link to Tetra's Curseforge page:
https://www.curseforge.com/minecraft/mc-mods/tetra

**Comment by MythrilBagels** [comment]
Hi Canada! According to Nebula, Alloyed should work with Tetra as Tetra already has support for modded Steel and Bronze ingots.

**Comment by FortressNebula** [comment]
Yep. Can confirm. Tetra already supports common metals like steel or bronze, so no extra compat stuff is needed. Our materials already work with Tetra.
