### ISSUE TITLE
bad FD steel knife recipe

### ISSUE THREAD

**Issue by TomasTobrman** [MythrilBagels/Create-Alloyed#17]
VERSIONS
Minecraft - 1.18.1
Create - 0.4d
Flywheel - 0.6.0
Alloyed - 0.1a

DESCRIPTION
The recipe for the Farmer's Delight steel knife in the Create Mechanical Crafters instead produces the steel axe.

STEPS TO REPRODUCE
JEI recipes

(edit: better description)

**Comment by FortressNebula** [comment]
Dammit, you're right! Thanks for bringing this to our attention. Will be fixed in the next update.
