### ISSUE TITLE
Mod fails on all Shears related items (Leaves/Vines/Etc)

### ISSUE THREAD

**Issue by ozma6464** [MythrilBagels/Create-Alloyed#21]
Shears are making errors on server startup
Every item related to shears are throwing this error: Couldn't parse loot modifier 

Error logs and Mod list is included as attachments

[latest.log](https://github.com/MythrilBagels/Create-Alloyed/files/8164180/latest.log)
[Cropped Logs of Errors.txt](https://github.com/MythrilBagels/Create-Alloyed/files/8164182/Cropped.Logs.of.Errors.txt)

![Mod Capture 1](https://user-images.githubusercontent.com/100719833/156234265-12ed4053-de9a-4bf5-b69e-4cd3f5545ca9.PNG)
![Mod Capture 2](https://user-images.githubusercontent.com/100719833/156234678-5a29b171-d8c8-496c-975e-263481379d41.PNG)

**Comment by FortressNebula** [comment]
Ah, thanks for bringing this to our attention! I recognize what would be causing that issue so I'll fix it as soon as I can! Hang tight until then!

**Comment by ozma6464** [comment]
i see that you closed this but have not released an update to resolve it. Just curious on an ETR?
