### ISSUE TITLE
Some features I would like to see added

### ISSUE THREAD

**Issue by SPAZ97** [MythrilBagels/Create-Alloyed#24]
**Bronze Friction Bearing** 
Bronze in reality has low friction against other metals, and is still used in bearings today.
My idea is that you could make a mechanical block out of bronze that would have two functions: increase stress capacity and prevent block breakage caused by misaligned rotation.
It would have a shaft attachment on two ends and a slit on top for attaching a large cogwheel. When one end receives a rotation, it is outputted to the cogwheel, behaving similarly to the rotation speed controller, with the main difference being it rotates at the same speed, but with double the stress capacity. If you try to connect one bearing to another the large cogwheel on the first one will break, thus preventing broken mechanics. Any component that is directly or indirectly connected to this bearing will not break due to stress.

**Steel-toed Work Boots**
Similar to Diving Boots, allows you to walk on belts, but without the ability to walk underwater. When you land on top of something, your fall damage is applied to whatever you fell onto, allowing you to basically "goomba stomp" things. Could be made with leather boots and two steel sheets.

**Steel Wool**
Used as an alternative to sandpaper to polish rose quartz, but with a higher durability. Created by processing a steel sheet in a millstone.

**Comment by FortressNebula** [comment]
Thank you for the suggestion!

1. A Bronze Friction Bearing, even with the limitations you described, would still likely be a pretty overpowered block. Preventing them from being used with one another would likely require analysing the entire rotation network, and would probably still leave gaps for players to misuse them.

2. Steel-toed Work Boots are an interesting idea, but will likely be implemented as a feature of Steel Boots when the entire Steel Armourset is added, not as an item in its own right.

3. Steel Wool is also an interesting idea, although CC&A's Diamond Grit Sandpaper accomplishes the same thing, and sandpaper is automateable anyway.

**Comment by SPAZ97** [comment]
Thank you for considering my ideas! I understand the friction bearing could possibly be abused, however if I could find a way to implement it in an efficient and effective way, would you perhaps add it to your mod? I have some experience in modding and I have dabbled with making add-ons for Create, so I know how it works. I also feel like the idea of using the abilities of the work boots on the steel boots is interesting, but I would rather see the regular steel armor be just armor, as having a full armor set with parts of it having special abilities doesn't quite sound right to me, though that's just me. Also, the steel wool would be a tier below the diamond grit sandpaper from CC&A, perhaps 1/2 or 3/4 the durability.
