### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by DigitalWendigo** [MythrilBagels/Create-Alloyed#25]
Hello! I'm sorry to bother you. 

I love the mod and the fact that it adds steel tools, as that really fills in a gap if you use something to limit progression through metal tiers. 
Adding to that, I would love to see steel armor being implemented as well. 

Many other mods that add steel items don't balance all that well when you add something like the Create Addon called "Create Stuff Additions". 
Which, adds zinc, copper and brass armor and tools. 
Allowing one to effectively add a fixed progression. 
Your mod fills in the final missing gap between brass and diamond.
Now arguably one could add them through getting a different mod and altering item properties, but that's a nightmare and a half to do. 
(Not saying that my suggestion isn't, since I have no understanding of coding.)
But would it be possible to see steel armor being implemented as well?

**Comment by FortressNebula** [comment]
It would be possible to see steel armour being implemented! In fact, we do plan to add steel armour of some sort soon!

**Comment by DigitalWendigo** [comment]
> It would be possible to see steel armour being implemented! In fact, we do plan to add steel armour of some sort soon!

That's fantastic news! I can't wait to see it. 
It will finally let me complete the modpack I've been trying to make for roughly a year. 
Thank you for all your work!
