### ISSUE TITLE
Steel Armor

### ISSUE THREAD

**Issue by TheEveEye** [MythrilBagels/Create-Alloyed#28]
Just add Steel Armor because there are already all the tools. I need this because my Iron armor always breaks super fast so the extra durability would help. Maybe 1000 Durability.

**Comment by MythrilBagels** [comment]
![image](https://user-images.githubusercontent.com/52741226/167840193-c49bd976-738f-4999-b7bd-9816462399cc.png)
;)

**Comment by Dr-WeiAL** [comment]
But the chain armor doesn't seem to have a way to get it?
![image](https://user-images.githubusercontent.com/47446553/169666305-a972b3eb-48c7-45e3-b60e-4c837e6c4db4.png)
