### ISSUE TITLE
latest create alloyed not compatible with minecraft 1.18.1

### ISSUE THREAD

**Issue by superdude808** [MythrilBagels/Create-Alloyed#29]
VERSIONS
Minecraft - 1.18.1
Create - create-mc1.18.1_v0.4f
Flywheel - flywheel-forge-1.18-0.6.1
Alloyed - alloyed-1.18.2-v1.3c

DESCRIPTION
https://pastebin.com/bSkRxGZD
game crashes on attempting to load alloyed v1.3c
because it requires a version of the forge mod loader that doesn't exist for minecraft 1.18.1
it will crash and say it needs fml loader v40 and that it found v39 instead
STEPS TO REPRODUCE
attempt load alloyed 1.3c on minecraft 1.18.1 which it is listed as being compatible with on curseforge 
https://imgur.com/a/b0u66nr

**Comment by FortressNebula** [comment]
Ah, the version needs to be modified to state that it isn't compatible with 1.18.1. Thanks for noticing that!
