### ISSUE TITLE
Steel Blocks

### ISSUE THREAD

**Issue by gamenTV** [MythrilBagels/Create-Alloyed#31]
VERSIONS
Minecraft - 1.18.2
Create - 0.4.1
Flywheel - 0.6.2
Alloyed - 1.3c

DESCRIPTION
idk if that should be like that but every single steel block is "unbreakable" (hard to mine no drop with pickaxe)

**Comment by FortressNebula** [comment]
What tier of pickaxe are you using?

**Comment by gamenTV** [comment]
Diamond Pickaxe

**Comment by FortressNebula** [comment]
That's strange, what other mods are you using?

**Comment by gamenTV** [comment]
[modlist.txt](https://github.com/MythrilBagels/Create-Alloyed/files/8793119/modlist.txt)

**Comment by FortressNebula** [comment]
Hmm, can you see if the error still occurs with only alloyed? (as well as create and flywheel since those are required)

**Comment by gamenTV** [comment]
The error still occurs

**Comment by FortressNebula** [comment]
Sorry, we can't reproduce the error. It's working just fine on our end. I'd recommend seeing if any of the other mods you're using mess around with loot tables or tools?

**Comment by gamenTV** [comment]
Sorry I just tried again I meant the Steel **Sheet** Metal blocks

**Comment by FortressNebula** [comment]
Ah, you're right. I'll fix that immediately. Thanks!
