### ISSUE TITLE
Not compatible with Create 0.5

### ISSUE THREAD

**Issue by jusipat** [MythrilBagels/Create-Alloyed#32]
Recent released version of Create does not work with Create Alloyed 1.18-v1.3d.
Crash report: https://pastebin.com/vtH5sR2x

VERSIONS
Minecraft - 1.18.2
Create - v0.5.0
Flywheel -1.18-0.6.3
Alloyed - v1.3d

DESCRIPTION
Game does not launch on startup with latest version of Create.

STEPS TO REPRODUCE
Install Create v0.5.0

**Comment by FortressNebula** [comment]
We are aware of this, the update literally just happened and most create addons no longer work for he newest update. Please be patient and wait for the next update.
