### ISSUE TITLE
Create alloyed crashes when loaded with the latest version of create and 

### ISSUE THREAD

**Issue by Warhand** [MythrilBagels/Create-Alloyed#34]
To submit an issue, just copy-paste everything beneath this line and swap out the brackets for your stuff, as well as attaching a crash log:

VERSIONS
Minecraft - [1.18.2 ]
Create - [ 0.5.0b ]
Flywheel - [ 0.6.4 ]
Alloyed - [ 1.4a ]

DESCRIPTION
The mod should load normally, but attempting to load it in forge version 40.1.55 results in a crash after the game finishes loading.
The issue also occurs with every forge version after the noted version, this has been tested up until 40.1.60

STEPS TO REPRODUCE
Install create alloyed and its dependencies and load them with forge version 40.1.55, the game will crash directly after loading

LOGS AND CRASH REPORT
Latest log: https://pastebin.com/BiwYYtf4
Crash report: https://pastebin.com/vTNuNf6m

**Comment by Ilaskus** [comment]
I have this exact same issue. It also says "Failed to create mod instance" after the latest update and keeps crashing the game.

**Comment by Ilaskus** [comment]
It'd seem like Curseforge will "reverse update" this mod back to 1.4a instead of updating it to 1.4b, I've tried updating it to 1.4b via the Versions section and all things worked out fine. Might be an issue with updating, I think?

**Comment by FortressNebula** [comment]
Yeah this seems like an issue on Curseforge's side, since we have indeed release v1.4b specifically to fix this problem.
