### ISSUE TITLE
Create-Alloyed doesn't let Minecraft open on newer versions of Forge

### ISSUE THREAD

**Issue by McInnescraft** [MythrilBagels/Create-Alloyed#42]
VERSIONS
Minecraft - [ Forge 1.18.2 40.1.60 ]
Create - [ 1.18.2_v0.5.0 ]
Flywheel - [ 1.18-0.6.3 ]
Alloyed - [ 1.18.2-v1.4b ]

DESCRIPTION
[ Minecraft doesn't open with newer versions of forge. Sorry if this is irrelevant since the last update was a while ago, but I saw someone in the comments say they couldn't open it. So I'm putting what is their problem (most likely) ]

STEPS TO REPRODUCE
[ Run Forge on 40.1.60 and it wont open. it does seem to still work on 40.1.0 ]

**Comment by FortressNebula** [comment]
Interesting, will investigate.

**Comment by FortressNebula** [comment]
This is not a problem with Forge, but with the version of Create you are using. You need to use the latest update for Create.
