### ISSUE TITLE
Mod Load Error

### ISSUE THREAD

**Issue by ZEROX7** [MythrilBagels/Create-Alloyed#44]
hey there so hteres the new flyweehl version 0.6.5 and your mods states 0.6.3 or above but wehn i launch it i get this
![image](https://user-images.githubusercontent.com/12628051/184706922-9f501128-b437-4c8a-a343-198b6169a902.png)

**Comment by FortressNebula** [comment]
Yes the mod currently does not work with the latest version of Create/Flywheel. We're working on it.
