### ISSUE TITLE
Apexhosting server crash when mod is installed

### ISSUE THREAD

**Issue by Papaturts** [MythrilBagels/Create-Alloyed#6]
VERSIONS
Minecraft - [1.16.5]
Create - [ create-mc1.16.5_v03.2g ]
Flywheel - [flywheel-1.16-0.2.5  ]
Alloyed - [alloyed-1.16.5-v0.1 ]

DESCRIPTION

I tried to add the mod to our server and it instantly crashes

STEPS TO REPRODUCE
install on server

[crash-2022-01-09_19.53.29-fml (1).txt](https://github.com/MythrilBagels/Create-Alloyed/files/7835846/crash-2022-01-09_19.53.29-fml.1.txt)

**Comment by MythrilBagels** [comment]
Thanks for bringing this to our attention. It's being worked out and should be fixed in the next minor update!

**Comment by FortressNebula** [comment]
This bug has been fixed in the v1.0 patch.
