### ISSUE TITLE
Fabric compatibility

### ISSUE THREAD

**Issue by obvionaoe** [MythrilBagels/Create-Alloyed#60]
Hi, would it be possible to add Fabric compatibility for this mod?

Thanks

**Comment by TodAufDerFlutch** [comment]
I'd love to see Fabric compatibility.

**Comment by poly2it** [comment]
I too, would love to see Fabric compatibility.

**Comment by FortressNebula** [comment]
I'm afraid as it stands, we don't really have the time to maintain both forge and fabric versions of the mod. Perhaps in the future?
