### ISSUE TITLE
[1.19.2] Mod Failed to Load Crash

### ISSUE THREAD

**Issue by Jusey1** [MythrilBagels/Create-Alloyed#63]
Crash Log:
[crash-2022-12-19_21.14.34-fml.txt](https://github.com/MythrilBagels/Create-Alloyed/files/10264160/crash-2022-12-19_21.14.34-fml.txt)

From my understanding of the crash log, it is unable to find something that isn't there in the main Create mod causing an "NoSuchMethodError" to happen.

**Comment by FortressNebula** [comment]
Please redo the issue following the issue template.

**Comment by Jusey1** [comment]
I was not given a template when making the issue though.
