### ISSUE TITLE
Error loading the mod on version 1.18.2

### ISSUE THREAD

**Issue by AlexMaudov** [MythrilBagels/Create-Alloyed#66]
I don't know what to say here. In general, when starting the game with the latest version of the mod for 1.18.2, I get this error, saying "there is no such method - com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.create(java.lang.String)". I attach a text file fml crash

PS: the mod version was alloyed-1.18.2-v1.4e, downloaded from curseforge.

[crash-2022-12-24_10.54.33-fml.txt](https://github.com/MythrilBagels/Create-Alloyed/files/10298142/crash-2022-12-24_10.54.33-fml.txt)

**Comment by AlexMaudov** [comment]
Additionally: Checked the previous version of the mod, alloyed-1.18.2-v1.4d
It loads calmly and does not give errors

**Comment by Proxwian** [comment]
What version of Create do you have?

**Comment by FortressNebula** [comment]
^ that.
Please make sure you're using the latest version of create for 1.18.2

**Comment by StormDragon-64** [comment]
Does the latest version of alloyed for 1.18.2 only work with 0.5g? I have some other addons still on 0.5e, so I am wondering if I have to use alloyed 1.4d instead. It doesn't say 0.5g is required on 1.4e's update changelog.

**Comment by FortressNebula** [comment]
Yep, the latest version is needed.
