### ISSUE TITLE
Steel Sheet Metal not using correct tool

### ISSUE THREAD

**Issue by Crows-Parliament** [MythrilBagels/Create-Alloyed#68]
Steel sheet metal should be mineable with a wooden pickaxe, and have a strength of 5, to correspond to create:deco sheet metals, currently it has the same properties as steel blocks

version 1.19.2

**Comment by FortressNebula** [comment]
Yep, this is intentional. Steel Sheet Metal is intentionally harder to mine and stronger than ordinary sheet metal since its made of steel.
