### ISSUE TITLE
Items/Blocks i would like to see!

### ISSUE THREAD

**Issue by 98Ulamog** [MythrilBagels/Create-Alloyed#7]
Hi, im 98Ulamog#7702 on discord, and big fan of this mod. Since your sneak peeks on the channel, i traveled with my creativity with this add-on. Art style is sure great, but the implementation of the 2 alloys, with their balanced recipes, is even greater.

Every day i imagine how some **Bronze casing** would fito soo well (even though i imagine you're already been thinking about it), and, taking inspirations from _Create Stuff Addition_, a cool **Steel Exoskeleton** (maybe taking from Andensite and Brass one), and so on.

Can't wait to see how the Bronze bell will work, too!

Obviously i don't really imagine the potential for this mod, that has the power to bring new alloys. But as I said I'm a big fan of this project. 

P.S.: not rreally an issue, but I like to be your fan! Great job to everyone!

**Comment by 98Ulamog** [comment]
i dont know how to put labels, but i hope this is a welcome "issue"

**Comment by FortressNebula** [comment]
first off, thanks a lot for the kind words! btw yes, bronze casing is planned!
