### ISSUE TITLE
Steel mesh fence

### ISSUE THREAD

**Issue by berob54** [MythrilBagels/Create-Alloyed#71]
Steel mesh fence renders as a purple and black cube when placed but still has the fence hitbox.
![image](https://user-images.githubusercontent.com/130937957/232346952-b64c4e05-6a60-4bed-bafb-d1c5f89b3ff2.png)

**Comment by Gryphontrainer** [comment]
I am also getting this issue, It seems to be caused by a connection?, to Create Deco. since I updated create deco while being on an older version of Alloyed but still got the issue.

**Comment by sijalids** [comment]
this is something the dev of create deco said: I changed how the fence models work in 1.3.0, so until Alloyed updates to match then yeah they'll be a little broken visually.

**Comment by FortressNebula** [comment]
Fixed!
