### ISSUE TITLE
Key Conflict

### ISSUE THREAD

**Issue by Dr-WeiAL** [MythrilBagels/Create-Alloyed#76]
Hi, I found that the itemGroup key in the language file of this mod is not specific to this mod, which will cause conflicts with the keys of other mods, I suggest you change "itemGroup.main_group" to "itemGroup.create_alloyed"
![image](https://github.com/MythrilBagels/Create-Alloyed/assets/47446553/da4f23ba-7b9f-4a29-914e-84e7969d80d8)

**Comment by FortressNebula** [comment]
Fixed!
