### ISSUE TITLE
Strange issue with sliding steel doors causing blocks to not be mineable and other issues

### ISSUE THREAD

**Issue by ace-astra0** [MythrilBagels/Create-Alloyed#77]
![error message](https://github.com/MythrilBagels/Create-Alloyed/assets/134647680/f83fcb1f-8ec8-4ff7-83de-c92ee12f6131)

I noticed that most pickaxe-mineable blocks were being broken by Alloyed by checking my latest.log and found that sliding steel doors weren't being registered by the game properly and invalidating a bunch of important tags. I am not sure what is causing the doors not to load at all - I was able to replicate the same issue in an environment with only Create and Alloyed installed, nothing else

**Comment by FortressNebula** [comment]
Fixed.
