### ISSUE TITLE
Alloyed 5.1 doesn't register pickaxes

### ISSUE THREAD

**Issue by Klouver-github** [MythrilBagels/Create-Alloyed#79]
So I am trying to mine stone block with a wooden pickaxe, stone pickaxe, iron pickaxe, even a steel pickaxe but it doesn't register or see I can mine it, like other times this issues I had before. I take out Alloy I can use pickaxes, but if I have alloy in mod folder I can not use pickaxes

**Comment by poly-1810** [comment]
ive noticed this bug too, using tinkers construct pickaxes, vanilla pickaxes, and anything that counts as a "pickaxe" cant mine stone, its likely due to the mod somehow removing the mineable via pickaxe tag

**Comment by FortressNebula** [comment]
Could you give versions? Plus what other mods you're using, because thats definitely not a bug we encountered in dev.

**Comment by waj171** [comment]
Getting the same with 
alloyed-1.18.2-v1.5a.jar

Forge: 40.2.8
Create: 0.5.1.b

**Comment by NightmareTwilight** [comment]
The exact cause of this issue seems to be this: 

> Couldn't load tag minecraft:mineable/pickaxe as it is missing following references: alloyed:sliding_steel_door (from alloyed-1.18.2-v1.5a.jar), 
> 	alloyed:locked_sliding_steel_door (from alloyed-1.18.2-v1.5a.jar)

as mentioned in #77.

**Comment by FortressNebula** [comment]
Fixed!
