### ISSUE TITLE
Fabric Version Please.

### ISSUE THREAD

**Issue by ghost** [MythrilBagels/Create-Alloyed#87]
Hello,
I am a fellow member of the Create Steam n' Rails Community Minecraft Server.
However, i have requested a change to Fabric with the following message in the discord: 
Forge is getting a little bit old, and its starting to show with most mod's original version now starting to be Fabric, not forge. This shows in Modrinth, where the most used mod loader is now Fabric. All mods that are in the first page of Modrinth support Fabric. Some even ONLY supporting Fabric. This shows with Sodium, Lithium and Iris Shaders. But we arent going to talk about just Modrinth, are we? When we apply the Fabric Mod loader filter in curseforge's mc-mods, website, the first page... Doesnt even change. Lets take a look at a very popular mod. WTHIT, It is a mod that shows the name of the object, and if it is from Minecraft, or some other 3rd party mod. And guess what? WTHIT has Fabric as its main mod loader. For Forge, you have to download a "WTHIT Forge Edition" I hope this encourages you to change to fabric. You can look more in to it, because im not going to waste hours to just make one server change to Fabric.

But as we all know,
This mod isn't compatible with Fabric.
So i'm here to request a Fabric version.
Thank you.

**Comment by QianFuv** [comment]
+1 fabric！！！！
