### ISSUE TITLE
crash startup [1.19.2] forge

### ISSUE THREAD

**Issue by GitJhopa** [MythrilBagels/Create-Alloyed#95]
![image](https://github.com/MythrilBagels/Create-Alloyed/assets/86250668/810b5860-3f28-4bab-b65c-c2b41959901a)

**Comment by GitJhopa** [comment]
[crash-2023-07-03_13.50.15-fml.txt](https://github.com/MythrilBagels/Create-Alloyed/files/11936044/crash-2023-07-03_13.50.15-fml.txt)

**Comment by GitJhopa** [comment]
The player cannot enter the game

**Comment by GitJhopa** [comment]
i delete this fckng crashing mod

**Comment by HanatakeYurii** [comment]
It's working perfectly fine on my side, so something is going wrong on yours.
Was it a new world or a world you used Create: Alloyed in before?

You have too many mods to let anyone guess what's going wrong. You should narrow the list down to see if it's work without unrelated mods, then add more mods if it works. Unless you do that, I fear no one will be able to help you.

**Comment by GitJhopa** [comment]
I delete this mod. And I'm not going to do business with him again. It is from 1.16.5 versions of such a curve.
